management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 8081
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.framework.demo.mybatis.entity

spring:
  application:
    name: demo
  datasource:
    username: suyouliang
    password: '%M5sCQXNUq'
    url: jdbc:mysql://121.40.156.55:3306/test_db?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    #hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 600000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      config:
        contextPath: /nacos
        server-addr: http://121.40.156.55:8848
      discovery:
        namespace: public
        server-addr: http://121.40.156.55:8848
    loadbalancer:
      cache:
        caffeine:
          spec:
  config:
    import:
      - nacos:demo.yaml?refresh=true
  redis:
    database: 0
    host: http://121.40.156.55
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 1200
  main:
    allow-circular-references: true
